#!/usr/bin/env node
/**
 * Generate tokens.css from theme tokens.json files and sync into every
 * framework that declares a tokens.sync target in its uikit.yml registry.
 *
 *   node scripts/generate-css.mjs              # all themes
 *   node scripts/generate-css.mjs themes/name  # one theme
 *
 * Output:
 *   themes/<name>/tokens.css                   canonical generated file
 *   + one copy per frameworks registry entry
 *     (frameworks/<name>/uikit.yml -> tokens.sync)
 */

import { readFile, writeFile, mkdir, readdir } from "node:fs/promises";
import { basename, dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const FRAMEWORKS_DIR = join(ROOT, "frameworks");

const MODE_SELECTOR = {
  light: ":root",
  dark: '[data-theme="dark"]',
};

async function frameworkSyncTargets() {
  const targets = [];
  let entries;
  try {
    entries = await readdir(FRAMEWORKS_DIR, { withFileTypes: true });
  } catch {
    return targets;
  }
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const dir = join(FRAMEWORKS_DIR, entry.name);
    const registryPath = join(dir, "uikit.yml");
    let registry;
    try {
      registry = parseYaml(await readFile(registryPath, "utf8"));
    } catch {
      continue;
    }
    const sync = registry?.tokens?.sync;
    if (typeof sync !== "string" || !sync) {
      throw new Error(
        `${relative(ROOT, registryPath)}: missing tokens.sync target`,
      );
    }
    targets.push(join(dir, sync));
  }
  return targets;
}

function parseValue(value) {
  if (typeof value === "string") return { light: value };
  if (
    value &&
    typeof value === "object" &&
    "light" in value &&
    "dark" in value
  ) {
    return { light: String(value.light), dark: String(value.dark) };
  }
  throw new Error(`invalid token value: ${JSON.stringify(value)}`);
}

function header(themeName) {
  return [
    "/*",
    ` * Generated by scripts/generate-css.mjs from themes/${themeName}/tokens.json.`,
    " * Do not edit by hand — run the generator instead.",
    " *",
    " * All components consume tokens exclusively — no hardcoded colors, radii,",
    " * spacing, or shadows. Consumers theme the library by overriding any",
    " * subset of these custom properties, or by importing another theme.",
    " */",
    "",
  ].join("\n");
}

function render(themeName, schema, values) {
  const lines = [header(themeName)];
  const tierOrder = Object.keys(schema.tiers);
  for (const mode of ["light", "dark"]) {
    lines.push(`${MODE_SELECTOR[mode]} {`);
    for (const tier of tierOrder) {
      const tokens = values[tier] ?? {};
      const modeValues = Object.entries(tokens).filter(
        ([, v]) => mode !== "dark" || "dark" in parseValue(v),
      );
      if (modeValues.length === 0) continue;
      lines.push(`  /* ${tier} */`);
      for (const [token, value] of modeValues) {
        lines.push(`  --se-${tier}-${token}: ${parseValue(value)[mode]};`);
      }
    }
    lines.push("}", "");
  }
  return lines.join("\n").replace(/\n+$/, "\n");
}

async function main() {
  const arg = process.argv[2];
  const themeDirs = arg
    ? [resolve(ROOT, arg)]
    : (await readdir(join(ROOT, "themes"), { withFileTypes: true }))
        .filter((e) => e.isDirectory())
        .map((e) => join(ROOT, "themes", e.name));

  const targets = await frameworkSyncTargets();
  if (targets.length === 0) {
    console.warn("no frameworks/*/uikit.yml tokens.sync targets found");
  }

  for (const themeDir of themeDirs) {
    const themeName = basename(themeDir);
    const tokensPath = join(themeDir, "tokens.json");
    const [tokens, schema] = await Promise.all([
      readFile(tokensPath, "utf8").then(JSON.parse),
      readFile(join(ROOT, "specs/tokens.schema.json"), "utf8").then(JSON.parse),
    ]);
    const css = render(themeName, schema, tokens.values);
    await writeFile(join(themeDir, "tokens.css"), css);
    console.log(`wrote themes/${themeName}/tokens.css`);
    const syncs = arg ? themeName === basename(arg) : themeName === "default";
    if (syncs) {
      for (const targetPath of targets) {
        await mkdir(dirname(targetPath), { recursive: true });
        await writeFile(targetPath, css);
        console.log(`synced ${relative(ROOT, targetPath)}`);
      }
    }
  }
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});