#!/usr/bin/env node
/**
 * Generate tokens.css from a theme's tokens.json and sync it into every
 * consuming framework.
 *
 *   node scripts/generate-css.mjs [themes/<name>]   # default: themes/default
 *
 * Output:
 *   themes/<name>/tokens.css                        canonical generated file
 *   + one copy per entry in SYNC_TARGETS (path relative to repo root)
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const SYNC_TARGETS = [
  // Framework copy kept in sync; validated in CI by re-running the generator
  // and asserting a clean `git diff --exit-code`.
  "frameworks/react/lib/styles/tokens.css",
];

const MODE_SELECTOR = {
  light: ":root",
  dark: '[data-theme="dark"]',
};

function parseValue(value) {
  if (typeof value === "string") return { light: value };
  if (
    value &&
    typeof value === "object" &&
    "light" in value &&
    "dark" in value
  ) {
    return { light: String(value.light), dark: String(value.dark) };
  }
  throw new Error(`invalid token value: ${JSON.stringify(value)}`);
}

function header(themeName) {
  return [
    "/*",
    ` * Generated by scripts/generate-css.mjs from themes/${themeName}/tokens.json.`,
    " * Do not edit by hand — run the generator instead.",
    " *",
    " * All components consume tokens exclusively — no hardcoded colors, radii,",
    " * spacing, or shadows. Consumers theme the library by overriding any",
    " * subset of these custom properties, or by importing another theme.",
    " */",
    "",
  ].join("\n");
}

function emitSection(mode, tier, tokens, lines) {
  const selector = MODE_SELECTOR[mode];
  if (selector) lines.push(`${selector} {`);
  for (const [token, value] of Object.entries(tokens)) {
    const parsed = parseValue(value);
    if (mode === "dark" && !("dark" in parsed)) continue;
    lines.push(`  --se-${tier}-${token}: ${parsed[mode]};`);
  }
  if (selector) lines.push("}");
}

function render(themeName, schema, values) {
  const lines = [header(themeName)];
  const tierOrder = Object.keys(schema.tiers);
  for (const mode of ["light", "dark"]) {
    lines.push(`${MODE_SELECTOR[mode]} {`);
    for (const tier of tierOrder) {
      const tokens = values[tier] ?? {};
      const modeValues = Object.entries(tokens).filter(
        ([, v]) => mode !== "dark" || "dark" in parseValue(v),
      );
      if (modeValues.length === 0) continue;
      lines.push(`  /* ${tier} */`);
      for (const [token, value] of modeValues) {
        lines.push(`  --se-${tier}-${token}: ${parseValue(value)[mode]};`);
      }
    }
    lines.push("}", "");
  }
  return lines.join("\n").replace(/\n+$/, "\n");
}

async function main() {
  const arg = process.argv[2] ?? "themes/default";
  const themeDir = resolve(ROOT, arg);
  const themeName = arg.split(/[\\/]/).pop();
  const tokensPath = join(themeDir, "tokens.json");
  const schemaPath = join(ROOT, "specs/tokens.schema.json");

  const [tokens, schema] = await Promise.all([
    readFile(tokensPath, "utf8").then(JSON.parse),
    readFile(schemaPath, "utf8").then(JSON.parse),
  ]);

  const css = render(themeName, schema, tokens.values);
  const outPath = join(themeDir, "tokens.css");
  await writeFile(outPath, css);
  console.log(`wrote ${relative(ROOT, outPath)}`);

  for (const target of SYNC_TARGETS) {
    const targetPath = resolve(ROOT, target);
    await mkdir(dirname(targetPath), { recursive: true });
    await writeFile(targetPath, css);
    console.log(`synced ${relative(ROOT, targetPath)}`);
  }
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});